# Generated by Django 4.0.1 on 2022-01-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_anegdot_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anegdot',
            name='rating',
        ),
    ]
