# Generated by Django 3.2.5 on 2021-08-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scientists', '0002_rename_women_scientists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Почтовый идентификатор')),
                ('name', models.CharField(max_length=255, verbose_name='Имя в паспорте')),
                ('text', models.TextField(verbose_name='Доклад')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время доклада')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='scientists',
            options={'verbose_name': 'Учёный', 'verbose_name_plural': 'Ученые'},
        ),
        migrations.AlterField(
            model_name='scientists',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создание'),
        ),
    ]
