# Generated by Django 3.2.5 on 2021-08-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scientists', '0003_auto_20210823_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Доклад', 'verbose_name_plural': 'Доклады'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
