# Generated by Django 3.2.5 on 2021-09-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Science', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Научная статья', 'verbose_name_plural': 'Научные статьи'},
        ),
        migrations.AlterModelOptions(
            name='science',
            options={'verbose_name': 'Наука', 'verbose_name_plural': 'Науки'},
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст статьи'),
        ),
    ]
