# Generated by Django 4.0.1 on 2022-01-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anegdot',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anegdot',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
