# Generated by Django 4.0.1 on 2022-01-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_anegdot_rating_alter_anegdot_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anegdot',
            name='views',
        ),
    ]
