# Generated by Django 4.0.1 on 2022-01-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_smartphone_diagonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость, руб'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, руб'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='diagonal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Диагональ, дюймы'),
        ),
    ]
