# Generated by Django 4.0.1 on 2022-01-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cartproduct_cost_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
    ]
