# Generated by Django 4.0.1 on 2022-01-29 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_cartproduct_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chainsaw',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Длина шины, см')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объём двигателя, см')),
                ('power', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Мощность, л.с.')),
            ],
            bases=('main.product',),
        ),
    ]
