# Generated by Django 4.0.1 on 2022-01-29 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_chainsaw'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chainsaw',
            name='capacity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объём двигателя, см^3'),
        ),
    ]
