# Generated by Django 4.0.1 on 2022-02-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_comment_options_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Стоимость корзины, руб'),
            preserve_default=False,
        ),
    ]
