# Generated by Django 4.0.1 on 2022-02-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_cart_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость корзины, руб'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='Products', to='main.CartProduct', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='value',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
