# Generated by Django 4.0.1 on 2022-02-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_cart_cost_alter_cart_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='on_order',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='Products', to='main.CartProduct', verbose_name='Продукты'),
        ),
    ]
