# Generated by Django 4.0.1 on 2022-02-11 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_cart_on_order_alter_cart_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_delivery', models.DateTimeField(verbose_name='Дата и время доставки')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес доставки')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.cart', verbose_name='Заказ')),
            ],
        ),
    ]
