# Generated by Django 4.0.1 on 2022-02-17 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axe',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес, кг')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Длина, см')),
            ],
            bases=('main.product',),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_delivery',
            field=models.DateField(verbose_name='Дата доставки'),
        ),
    ]
